name: Tracker

on:
  schedule:
    #  3 h
    - cron: "0 */6 * * *"

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Make Changes and Commit
      run: |
       
        COMMITS=$(( RANDOM % 5 + 3 ))

        # Configurar el usuario de Git
        git config --global user.name "DanielHernandezGalvez"
        git config --global user.email "hernandezgalvezalejandro@gmail.com"

       
        for ((i=1; i<=COMMITS; i++))
        do
          echo "consulta del $(date)" >>tracking.txt
          git add .
          git commit -m "Se generó correctamente commit $i/$COMMITS"
        done

        # Push de todos los commits
        git push
