name: Tracker

on:
  schedule:
    #  3 h
    - cron: "0 */6 * * *"

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Make Changes
      run: |
        echo "consulta del $(date)" >>tracking.txt

    - name: Commit Changes
      run: |
        git config --global user.name "DanielHernandezGalvez"
        git config --global user.email "hernandezgalvezalejandro@gmail.com"
        git add .
        git commit -m "Se generó correctamente"
        git push
