name: Tracker

on:
  schedule:
    - cron: "0 */6 * * *"

concurrency:
  group: tracker-job
  cancel-in-progress: true

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Make Changes and Commit
        run: |
       
          git config --global user.name "DanielHernandezGalvez"
          git config --global user.email "hernandezgalvezalejandro@gmail.com"

       
          COMMITS=$(( RANDOM % 3 ))  # Puede ser 0, 1 o 2

     
          if [[ $COMMITS -eq 0 ]]; then
            echo "Esta ejecución no generará commits."
            exit 0
          fi

       
          for ((i=1; i<=COMMITS; i++))
          do
            echo "consulta del $(date)" >> tracking.txt
            git add tracking.txt
            git commit -m "Commit automático $i/$COMMITS: $(date)"
          done

          # Push de los commits realizados
          git push
